name: Transfer_Files API CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests with curl
        run: |
          echo "🔨 Building Docker image..."
          docker build -t myapp:test .

          echo "🚀 Starting container..."
          docker run -d -p 8080:8080 --name test-container myapp:test

          echo "⏳ Waiting for app to start..."
          sleep 3

          echo "🔍 Running curl test..."
          curl -f http://localhost:8080 || (echo "❌ App did not respond" && exit 1)

          echo "📤 POST /upload"
          curl -f -X POST http://localhost:8080/upload -F "file=@./test.txt"

          echo "🗑️ DELETE /files/test.txt"
          curl -f -X DELETE http://localhost:8080/files/test.txt

          echo "✅ Test passed!"

      - name: Cleanup
        if: always()
        run: |
          echo "🧹 Cleaning up..."
          docker stop test-container || true
          docker rm test-container || true
